spring.application.name=hc-backend
server.port=7000
spring.datasource.username=postgres
spring.datasource.password=8462
spring.datasource.url=jdbc:postgresql://db-hc-postgres:5432/app-hc
spring.jpa.hibernate.ddl-auto=update

